services:
     PROD:
       image: mod-nso-prod:${VER}
       container_name: nso_prod
       network_mode: none
       profiles:
             - prod
       environment:
             - EXTRA_ARGS=--with-package-reload
             - ADMIN_USERNAME=admin
             - ADMIN_PASSWORD=admin
       ports:
             - "2023:2024"
             - "8889:8888"
       volumes:
             - type: bind
               source: './NSO-vol/nso/etc'
               target: '/nso/etc'
             - type: bind
               source: './NSO-vol/nso/run'
               target: '/nso/run'
             - type: bind
               source: './NSO-log'
               target: '/logs'
             - type: bind
               source: './NSO-vol/nso-config/ncs.conf'
               target: '/etc/ncs/ncs.conf'
       healthcheck:
            test: ncs_cmd -c "wait-start 2"
            interval: 5s
            retries: 5
            start_period: 10s
            timeout: 10s
     BUILD:
            image: mod-nso-dev:${VER}
            container_name: nso-build
            network_mode: none
            profiles:
                - build
            volumes:
                - type: bind
                  source: './NSO-vol/nso/run/packages'
                  target: '/packages'
                - type: bind
                  source: './NSO-log/'
                  target: '/logs'
            command: /bin/bash -c "make all -C /packages/ && sleep infinity"